### PR TITLE
Rename virtual_cohort to virtual_study

### PR DESCRIPTION
**Pull request by kalletlak**

### CODE REVIEW

**Comment by jjgao** [comment]
@mandawilson would you please prioritize this? We hope this can be with the next portal release in a week or so. Thanks.

**Comment by kalletlak** [comment]
virtual_cohort feature is not in production till now. I hope there shoudn't be anything in it.

**Comment by zhx828** [comment]
Yeah, we could directly remove that collection.

**Comment by zhx828** [comment]
Just one quick comment, we should increase the pom version.

**Comment by kalletlak** [comment]
Since we did not release the master branch till now. not sure whether is a good plan to update version

**Comment by zhx828** [comment]
@mandawilson what do you think of the version issue?

**Pull request merged**
