### PR TITLE
Dockerize session service

### PR DESCRIPTION
**Pull request by oplantalech**
Improve current Dockerfile so that session service can be fully dockerized.

### CODE REVIEW

**Comment by Sjoerd-van-Hagen** [comment]
@inodb when do you have time for this one?

**Comment by inodb** [comment]
@oplantalech does the `dockerfile-maven-plugin` not work with multistage docker files?

**Comment by oplantalech** [comment]
@inodb Not sure. I think by removing it we keep the structure simpler.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao can you have a look at this now Ino is on holiday?

**Comment by inodb** [comment]
Thanks @Sjoerd-van-Hagen and @oplantalech !

**Pull request merged**
